import { Sequelize } from 'sequelize';
import dotenv from 'dotenv';

dotenv.config();

const sequelize = new Sequelize(
  process.env.DB_NAME,
  process.env.DB_USER,
  process.env.DB_PASSWORD,
  {
    host: process.env.DB_HOST,
    port: process.env.DB_PORT || 3306,
    dialect: 'mysql',
    logging: process.env.NODE_ENV === 'development' ? console.log : false,
    define: {
      timestamps: false, // We'll manage timestamps manually where needed or use Sequelize default options per model
      underscored: true  // Matches snake_case columns generated by JPA
    },
    timezone: '+05:30' // Align with India Standard Time or UTC
  }
);

export default sequelize;
